In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [19]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Zero dimentional array

In [4]:
arr1=np.array((45))
print(arr)

[1 2 3 4 5]


# One dimentional array

In [5]:
arr4=np.array([1,2,3,4])
print(arr4)

[1 2 3 4]


# Two dimentional array

In [7]:
arr2=np.array([[1,2,3,4],[2,4,6,8]])
print(arr2)

[[1 2 3 4]
 [2 4 6 8]]


# Three dimentional array

In [8]:
arr3=np.array([[[1,2,3,4,],[5,6,7,8],[9,10,11,12],[4,5,6,11]]])
print(arr)

[1 2 3 4 5]


In [9]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
2
3
1


# Check the indexing of array

In [10]:
print(arr1)  
print(arr4[0])
print(arr2[0,1]) 
print(arr3[0,0,0])

45
1
2
1


# array slicing 

In [11]:
print(arr4[1:4])
print(arr4[1:4:2]) # start:end:step

print(arr2[1,1:4:2])

[2 3 4]
[2 4]
[4 8]


# The use of copy and view 

In [12]:
arr=np.array([1,2,3,4,5])
copy_arr=arr.copy()
copy_arr[0]=2
print(arr)
print(copy_arr)

[1 2 3 4 5]
[2 2 3 4 5]


In [13]:
ar=np.array([2,3,4,5,6])
view_arr=ar.view()
view_arr[0]=1
print(ar)
print(view_arr)

[1 3 4 5 6]
[1 3 4 5 6]


In [14]:
print(ar[::2])

[1 4 6]


# Check the shape 

In [19]:
shape_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(shape_arr.shape)

(2, 4)


In [20]:
check_arr=np.array([1,2,3,4,5],ndmin=5)
print(check_arr)
print("shape of array:",check_arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of array: (1, 1, 1, 1, 5)


# Reshape the array

In [21]:
reshape_arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_reshape_arr=reshape_arr.reshape(4,3)
print(new_reshape_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# looping in array

In [ ]:
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)

In [ ]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr1:
    for y in x:
        print(y)

# adding 

In [ ]:
x=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
y=np.array([[1,2,3,4,6],
            [2,3,4,5,6]])
z=x+y
print(z)

[[ 2  4  6  8 11]
 [ 3  5  7  9 11]]


# subtraction

In [31]:
x=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
y=np.array([[1,2,3,4,6],
            [2,3,4,5,6]])
z=y-x
print(z)

[[0 0 0 0 1]
 [1 1 1 1 1]]


# multiply element wise 

In [ ]:
x=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
y=np.array([[1,2,3,4,6],
            [2,3,4,5,6]])
z=x**y
#z=x*y
print(z)

[[    1     4    27   256 15625]
 [    1     8    81  1024 15625]]


# actual multiply

In [40]:
x=np.array([[1,2,3,4,5],
            [1,2,3,4,5]])
y=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8],
            [9,10]])
z = x @ y
print(z)

[[ 95 110]
 [ 95 110]]


# devide 

In [ ]:
x=np.array([[10,20,30],
            [40,50,60],
            [70,90,100]])
y=np.array([[1,2,3],
            [4,5,6],
            [7,9,10]])
#z=x/y
z=x//y
print(z)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


# Fetch ans with condition