In [17]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np


In [19]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


# Zero dimentional array

In [21]:
arr1=np.array((45))
print(arr)

[1 2 3 4 5]


# One dimentional array

In [25]:
arr4=np.array([1,2,3,4])
print(arr4)

[1 2 3 4]


# Two dimentional array

In [43]:
arr2=np.array([[1,2,3,4],[2,4,6,8]])
print(arr2)

[[1 2 3 4]
 [2 4 6 8]]


# Three dimentional array

In [23]:
arr3=np.array([[[1,2,3,4,],[5,6,7,8],[9,10,11,12],[4,5,6,11]]])
print(arr)

[1 2 3 4 5]


In [26]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

0
2
3
1


# Check the indexing of array

In [39]:
print(arr1)  
print(arr4[0])
print(arr2[0,1]) 
print(arr3[0,0,0])

45
1
2
1


# array slicing 

In [45]:
print(arr4[1:4])
print(arr4[1:4:2]) # start:end:step

print(arr2[1,1:4:2])

[2 3 4]
[2 4]
[4 8]


# The use of copy and view 

In [47]:
arr=np.array([1,2,3,4,5])
copy_arr=arr.copy()
copy_arr[0]=2
print(arr)
print(copy_arr)

[1 2 3 4 5]
[2 2 3 4 5]


In [50]:
ar=np.array([2,3,4,5,6])
view_arr=ar.view()
view_arr[0]=1
print(ar)
print(view_arr)

[1 3 4 5 6]
[1 3 4 5 6]


In [51]:
print(ar[::2])

[1 4 6]
